services:
  insights-of-a-trader:
    build:
      context: ../
      dockerfile: compose/DockerFile.prod
      target: production
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.15
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
