services:
  insights-of-a-trader:
    build:
      context: ../
      dockerfile: compose/DockerFile.prod
      target: production
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=5000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:14.15
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: application_user
      POSTGRES_PASSWORD: jg83ng37£T£j$
      POSTGRES_DB: insights-of-a-trader-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
